import Link from 'next/link'
import React from 'react'

const page = () => {
  return (
    <>
      {/* <section className='w-full h-screen flex justify-center'>
        <div className='w-full max-w-6xl flex justify-start border-2'>

          <aside className={`w-20 lg:w-25  z-10 h-full  p-4 flex flex-col border transition-all duration-300`}>
            <div className="h-full flex flex-col justify-between border-0">
              <nav className="flex flex-col gap-3 mt-15 lg:mt-20">
                <Link href="/category/all" className={`p-2 pl-0 rounded-md flex items-center gap-2 `}>All</Link>
                <Link href="/category/fruits" className={`p-2 pl-0 rounded-md flex items-center gap-2 `}>Fruits</Link>
                <Link href="/category/milk-dairy" className={`p-2 pl-0 rounded-md flex items-center gap-2 `}>Milk-Dairy</Link>
                <Link href="/category/bakery" className={`p-2 pl-0 rounded-md flex items-center gap-2 `}>Bakery</Link>
              </nav>


            </div>
          </aside>

        </div>
      </section> */}
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat fuga ullam repellat consectetur minima ab cupiditate illum exercitationem eum pariatur cumque mollitia nemo veritatis temporibus, ipsam accusamus reiciendis itaque sed odio hic nihil error. Labore numquam fugiat cum enim accusamus! Exercitationem, praesentium ratione nulla quisquam minima cumque cupiditate facere. Eos earum iure fugiat vero animi. Asperiores, tempore! Ipsa obcaecati consequatur veniam perspiciatis repellendus quae facilis itaque accusamus sit, magnam deserunt facere! Libero aliquid obcaecati laboriosam fugiat molestiae provident sapiente quidem cumque nostrum repudiandae perferendis cupiditate unde nobis sequi dicta recusandae, officiis cum odit reprehenderit? In obcaecati nisi esse soluta dolore? Sed at ducimus doloribus, sint minima deserunt nisi ad quod voluptatum atque suscipit ea fugiat vel esse excepturi minus eum natus! Repellat maxime voluptates recusandae nesciunt? Totam molestiae nam nobis ab atque, soluta sequi aspernatur pariatur, ex vitae possimus fugiat commodi voluptate quam. Dignissimos, quisquam commodi eos ullam amet doloremque recusandae sed corrupti temporibus ad sit veniam quam, inventore, suscipit libero. Dolore sed illum commodi praesentium sint. Sit rerum, eos dolor, esse voluptate illum tempore expedita sint, consequatur molestiae aut quibusdam quisquam fuga atque praesentium. Nulla, quaerat eius? Assumenda reiciendis veritatis accusamus autem at tenetur aliquid accusantium porro nihil amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat fuga ullam repellat consectetur minima ab cupiditate illum exercitationem eum pariatur cumque mollitia nemo veritatis temporibus, ipsam accusamus reiciendis itaque sed odio hic nihil error. Labore numquam fugiat cum enim accusamus! Exercitationem, praesentium ratione nulla quisquam minima cumque cupiditate facere. Eos earum iure fugiat vero animi. Asperiores, tempore! Ipsa obcaecati consequatur veniam perspiciatis repellendus quae facilis itaque accusamus sit, magnam deserunt facere! Libero aliquid obcaecati laboriosam fugiat molestiae provident sapiente quidem cumque nostrum repudiandae perferendis cupiditate unde nobis sequi dicta recusandae, officiis cum odit reprehenderit? In obcaecati nisi esse soluta dolore? Sed at ducimus doloribus, sint minima deserunt nisi ad quod voluptatum atque suscipit ea fugiat vel esse excepturi minus eum natus! Repellat maxime voluptates recusandae nesciunt? Totam molestiae nam nobis ab atque, soluta sequi aspernatur pariatur, ex vitae possimus fugiat commodi voluptate quam. Dignissimos, quisquam commodi eos ullam amet doloremque recusandae sed corrupti temporibus ad sit veniam quam, inventore, suscipit libero. Dolore sed illum commodi praesentium sint. Sit rerum, eos dolor, esse voluptate illum tempore expedita sint, consequatur molestiae aut quibusdam quisquam fuga atque praesentium. Nulla, quaerat eius? Assumenda reiciendis veritatis accusamus autem at tenetur aliquid accusantium porro nihil amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat fuga ullam repellat consectetur minima ab cupiditate illum exercitationem eum pariatur cumque mollitia nemo veritatis temporibus, ipsam accusamus reiciendis itaque sed odio hic nihil error. Labore numquam fugiat cum enim accusamus! Exercitationem, praesentium ratione nulla quisquam minima cumque cupiditate facere. Eos earum iure fugiat vero animi. Asperiores, tempore! Ipsa obcaecati consequatur veniam perspiciatis repellendus quae facilis itaque accusamus sit, magnam deserunt facere! Libero aliquid obcaecati laboriosam fugiat molestiae provident sapiente quidem cumque nostrum repudiandae perferendis cupiditate unde nobis sequi dicta recusandae, officiis cum odit reprehenderit? In obcaecati nisi esse soluta dolore? Sed at ducimus doloribus, sint minima deserunt nisi ad quod voluptatum atque suscipit ea fugiat vel esse excepturi minus eum natus! Repellat maxime voluptates recusandae nesciunt? Totam molestiae nam nobis ab atque, soluta sequi aspernatur pariatur, ex vitae possimus fugiat commodi voluptate quam. Dignissimos, quisquam commodi eos ullam amet doloremque recusandae sed corrupti temporibus ad sit veniam quam, inventore, suscipit libero. Dolore sed illum commodi praesentium sint. Sit rerum, eos dolor, esse voluptate illum tempore expedita sint, consequatur molestiae aut quibusdam quisquam fuga atque praesentium. Nulla, quaerat eius? Assumenda reiciendis veritatis accusamus autem at tenetur aliquid accusantium porro nihil amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat fuga ullam repellat consectetur minima ab cupiditate illum exercitationem eum pariatur cumque mollitia nemo veritatis temporibus, ipsam accusamus reiciendis itaque sed odio hic nihil error. Labore numquam fugiat cum enim accusamus! Exercitationem, praesentium ratione nulla quisquam minima cumque cupiditate facere. Eos earum iure fugiat vero animi. Asperiores, tempore! Ipsa obcaecati consequatur veniam perspiciatis repellendus quae facilis itaque accusamus sit, magnam deserunt facere! Libero aliquid obcaecati laboriosam fugiat molestiae provident sapiente quidem cumque nostrum repudiandae perferendis cupiditate unde nobis sequi dicta recusandae, officiis cum odit reprehenderit? In obcaecati nisi esse soluta dolore? Sed at ducimus doloribus, sint minima deserunt nisi ad quod voluptatum atque suscipit ea fugiat vel esse excepturi minus eum natus! Repellat maxime voluptates recusandae nesciunt? Totam molestiae nam nobis ab atque, soluta sequi aspernatur pariatur, ex vitae possimus fugiat commodi voluptate quam. Dignissimos, quisquam commodi eos ullam amet doloremque recusandae sed corrupti temporibus ad sit veniam quam, inventore, suscipit libero. Dolore sed illum commodi praesentium sint. Sit rerum, eos dolor, esse voluptate illum tempore expedita sint, consequatur molestiae aut quibusdam quisquam fuga atque praesentium. Nulla, quaerat eius? Assumenda reiciendis veritatis accusamus autem at tenetur aliquid accusantium porro nihil amet.


    </>
  )
}

export default page