import { Button } from "@/components/ui/button";
import Image from "next/image";
import { categoryImages } from "../../../assets/category icons/category images";

export default function Home() {
  return (
    <div className="flex items-center justify-center gap-3 flex-wrap p-10 pt-20">
      
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.fruits}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.vegetables}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      <Image
        src={categoryImages.sweets}
        alt="hi"
        width={200}
        height={200}
        className="rounded-md"
      />
      
    </div>
  );
}
