import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "@/components/ui/sonner"
import AuthProvider from "@/context/AuthProvider";
import { AppContextProvider } from "@/context/AppContext";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const outfit = Outfit({
  // variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${outfit.className} ${outfit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <AppContextProvider>
            <CartProvider>
              <ThemeProvider>
                <TooltipProvider>
                  {children}
                </TooltipProvider>
                <Toaster position="top-center" />
              </ThemeProvider>
            </CartProvider>
          </AppContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
