import {
    Coffee,
    UtensilsCrossed,
    MoonStar,
    Sandwich,
    Zap,
    Salad,
    Dumbbell,
    PartyPopper,
    Baby,
    Gift,
} from "lucide-react";

export const collections = [
    {
        label: "Breakfast",
        value: "breakfast",
        icon: Coffee,
    },
    {
        label: "Lunch",
        value: "lunch",
        icon: UtensilsCrossed,
    },
    {
        label: "Dinner",
        value: "dinner",
        icon: MoonStar,
    },
    {
        label: "Snacks",
        value: "snacks",
        icon: Sandwich,
    },
    {
        label: "Quick Meals",
        value: "quick-meals",
        icon: Zap,
    },
    {
        label: "Healthy",
        value: "healthy",
        icon: Salad,
    },
    {
        label: "High Protein",
        value: "high-protein",
        icon: Dumbbell,
    },
    {
        label: "Party",
        value: "party",
        icon: PartyPopper,
    },
    {
        label: "Kids",
        value: "kids",
        icon: Baby,
    },
    {
        label: "Festival",
        value: "festival",
        icon: Gift,
    },
];



export const subcategories: Record<string, string[]> = {
    "vegetables": [
        "Leafy Vegetables",
        "Root Vegetables",
        "Onion & Garlic",
        "Tomatoes",
        "Potatoes",
        "Beans & Peas",
        "Cabbage & Cauliflower",
        "Carrots",
        "Cucumber",
        "Capsicum",
        "Mushrooms",
        "Other Vegetables",
    ],

    "fruits": [
        "Apples",
        "Bananas",
        "Mangoes",
        "Oranges",
        "Grapes",
        "Pomegranate",
        "Watermelon",
        "Papaya",
        "Pineapple",
        "Guava",
        "Berries",
        "Other Fruits",
    ],

    "milk-dairy": [
        "Milk",
        "Curd & Yogurt",
        "Butter",
        "Cheese",
        "Paneer",
        "Cream",
        "Buttermilk",
        "Lassi",
        "Flavoured Milk",
        "Condensed Milk",
        "Milk Powder",
        "Other Dairy",
    ],

    "bakery": [
        "Bread",
        "Buns & Pav",
        "Cakes",
        "Pastries",
        "Muffins",
        "Cookies",
        "Donuts",
        "Croissants",
        "Rusk",
        "Pies",
        "Bakery Snacks",
        "Other Bakery",
    ],

    "rice-grains": [
        "Basmati Rice",
        "Regular Rice",
        "Brown Rice",
        "Poha",
        "Oats",
        "Quinoa",
        "Dalia",
        "Wheat",
        "Atta",
        "Maida",
        "Suji",
        "Other Grains",
    ],

    "spices": [
        "Whole Spices",
        "Ground Spices",
        "Masala Blends",
        "Chilli Powder",
        "Turmeric Powder",
        "Cumin",
        "Coriander",
        "Garam Masala",
        "Pepper",
        "Cardamom",
        "Cinnamon",
        "Other Spices",
    ],

    "snacks": [
        "Chips",
        "Namkeen",
        "Biscuits",
        "Cookies",
        "Popcorn",
        "Nachos",
        "Crackers",
        "Chocolates",
        "Protein Snacks",
        "Healthy Snacks",
        "Other Snacks",
    ],

    "drinks": [
        "Soft Drinks",
        "Fruit Juices",
        "Energy Drinks",
        "Sports Drinks",
        "Mineral Water",
        "Coconut Water",
        "Soda",
        "Health Drinks",
        "Milk Drinks",
        "Flavoured Water",
        "Cold Drinks",
        "Other Drinks",
    ],

    "tea-coffee": [
        "Tea",
        "Green Tea",
        "Black Tea",
        "Herbal Tea",
        "Tea Bags",
        "Coffee",
        "Instant Coffee",
        "Ground Coffee",
        "Cold Coffee",
        "Coffee Beans",
        "Hot Chocolate",
        "Other Tea & Coffee",
    ],

    "oil-ghee": [
        "Sunflower Oil",
        "Mustard Oil",
        "Groundnut Oil",
        "Olive Oil",
        "Rice Bran Oil",
        "Coconut Oil",
        "Soybean Oil",
        "Sesame Oil",
        "Blended Oil",
        "Ghee",
        "Butter",
        "Other Oils",
    ],

    "sweets": [
        "Indian Sweets",
        "Bengali Sweets",
        "Rasgulla",
        "Gulab Jamun",
        "Rasmalai",
        "Sandesh",
        "Kaju Sweets",
        "Ladoo",
        "Barfi",
        "Jalebi",
        "Halwa",
        "Other Sweets",
    ],

    "meat-chicken": [
        "Chicken",
        "Mutton",
        "Chicken Breast",
        "Chicken Wings",
        "Chicken Curry Cut",
        "Mutton Curry Cut",
        "Minced Meat",
        "Marinated Meat",
        "Sausages",
        "Kebabs",
        "Ready-to-Cook Meat",
        "Other Meat",
    ],

    "eggs": [
        "Regular Eggs",
        "Brown Eggs",
        "White Eggs",
        "Farm Eggs",
        "Organic Eggs",
        "Free-Range Eggs",
        "Protein Eggs",
        "Quail Eggs",
        "Egg Packs",
        "Boiled Eggs",
        "Egg Products",
        "Other Eggs",
    ],

    "fish": [
        "Rohu",
        "Katla",
        "Hilsa",
        "Pomfret",
        "Prawns",
        "Basa",
        "Tuna",
        "Salmon",
        "Crab",
        "Fish Fillets",
        "Other Fish",
    ],

    "frozen-food": [
        "Frozen Vegetables",
        "Frozen Fruits",
        "Frozen Chicken",
        "Frozen Fish",
        "Frozen Snacks",
        "Frozen Paratha",
        "Frozen Fries",
        "Frozen Pizza",
        "Frozen Momos",
        "Ice Cream",
        "Frozen Desserts",
        "Other Frozen Food",
    ],

    "ready-to-cook": [
        "Instant Noodles",
        "Pasta",
        "Momos",
        "Spring Rolls",
        "Paratha",
        "Ready Meals",
        "Instant Mixes",
        "Soup",
        "Cooking Kits",
        "Marinated Food",
        "Ready-to-Cook Snacks",
        "Other Ready to Cook",
    ],

    "dry-fruits": [
        "Almonds",
        "Cashews",
        "Raisins",
        "Walnuts",
        "Pistachios",
        "Dates",
        "Figs",
        "Apricots",
        "Prunes",
        "Mixed Dry Fruits",
        "Seeds",
        "Other Dry Fruits",
    ],
};  
